version: "3.9"
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
  server:
    depends_on:
      - database
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:

      # V___ПОПАВИТ ТУТ___V
      # Изменить ELASTIC_FULL_URL подставив свои значения <variables>
      ELASTIC_FULL_URL: https://<user>:<pass>@host.docker.internal:<port>
      # ___ПОПАВИТ СВЕРХУ___

      DB_USER: root
      DB_PASSWORD: secret
      DB_URL: database:3306/homestead
    ports:
      - "7878:7878"
